version: '2'


services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: weblogfacade
        ports:
            - "4000:4000"
    db:
        image: mongo:3.6.1
        container_name: mongodbta      
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: